name: Atualizar Modpack Automático

on:
  push:
    paths:
      - 'servers/bahpack-1.20.1/forgemods/required/**.jar'

jobs:
  construir-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar os ficheiros do repositório
        uses: actions/checkout@v4

      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo .env
        run: |
          echo "ROOT=${{ github.workspace }}" > .env
          echo "BASE_URL=https://raw.githubusercontent.com/${{ github.repository }}/main/" >> .env
          echo "JAVA_EXECUTABLE=$(which java)" >> .env

      - name: Gerar o JSON base com o Nebula
        run: npm run start -- generate distro

      - name: Executar o Injetor Cirúrgico (Cataclysm e MD5)
        run: node injetar.js

      - name: Guardar as alterações (Commit e Push)
        run: |
          git config --global user.name "Robô do Estúdio"
          git config --global user.email "actions@github.com"
          git add distribution.json
          git commit -m "🤖 JSON atualizado automaticamente pela Nuvem" || echo "Nenhuma alteração no JSON."
          git push
